In [7]:
import pandas as pd
import time

arquivo1=pd.read_csv("ArmasApreendidasEvolucaoCisp(1)2022.csv", sep=";", encoding="latin-1") #caminhos dos arquivos


inicio_tempo=time.time() #marcação do tempo de processamento
df_pandas=pd.concat([arquivo1])

display(df_pandas.head())

print("Tempo de execução com Pandas:", time.time() - inicio_tempo, "segundos")

  Soma de arma_fogo_total  Rótulos de Coluna   Unnamed: 2
0        Rótulos de Linha               2022  Total Geral
1                Setembro                515          515
2                 Outubro                488          488
3                Novembro                598          598
4             Total Geral               1601         1601

Tempo de execução com Pandas: 0.0029997825622558594 segundos

In [8]:
import pandas as pd
import time

arquivo1=pd.read_csv("ArmasApreendidasEvolucaoCisp(1)2023.csv", sep=";", encoding="latin-1") #caminhos dos arquivos


inicio_tempo=time.time() #marcação do tempo de processamento
df_pandas=pd.concat([arquivo1])

display(df_pandas.head())

print("Tempo de execução com Pandas:", time.time() - inicio_tempo, "segundos")

  Soma de arma_fogo_total  Rótulos de Coluna   Unnamed: 2
0        Rótulos de Linha               2023  Total Geral
1                Setembro                398          398
2                 Outubro                450          450
3                Novembro                463          463
4             Total Geral               1311         1311

Tempo de execução com Pandas: 0.0030050277709960938 segundos

In [9]:
import pandas as pd
import numpy as np

In [17]:
dados=pd.read_csv('ArmasApreendidasEvolucaoCisp.csv',sep=";")
display(dados.head())
estatistica=dados.describe()
display(estatistica)
df_copia=dados.copy()

,cisp,mes,ano,aisp,risp,arma_fogo_arma_fabricacao_caseira,arma_fogo_carabina,arma_fogo_espingarda,arma_fogo_fuzil,arma_fogo_garrucha,...,simulacro_fuzil,simulacro_garrucha,simulacro_garruchao,simulacro_metralhadora,simulacro_outros,simulacro_paintball,simulacro_pistola,simulacro_revolver,simulacro_submetralhadora,simulacro_total
0,1,1,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,2007,5,1,0,0,0,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,cisp,mes,ano,aisp,risp,arma_fogo_arma_fabricacao_caseira,arma_fogo_carabina,arma_fogo_espingarda,arma_fogo_fuzil,arma_fogo_garrucha,...,simulacro_fuzil,simulacro_garrucha,simulacro_garruchao,simulacro_metralhadora,simulacro_outros,simulacro_paintball,simulacro_pistola,simulacro_revolver,simulacro_submetralhadora,simulacro_total
count,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,...,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000
mean,81.581114,6.500000,2015.485472,20.701170,3.854722,0.089757,0.054883,0.445420,0.221079,0.088008,...,0.041722,0.001488,0.000276,0.001598,0.033675,0.001598,0.565972,0.023148,0.002480,0.740851
std,48.297678,3.452111,5.185393,11.415816,2.011673,0.730913,0.285896,1.094207,1.087289,0.363395,...,0.243463,0.051948,0.019640,0.041305,0.224992,0.039948,1.129567,0.154357,0.050837,1.360895
min,1.000000,1.000000,2007.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,38.000000,3.750000,2011.000000,10.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,78.000000,6.500000,2015.000000,21.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,125.000000,9.250000,2020.000000,31.000000,6.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,168.000000,12.000000,2024.000000,43.000000,7.000000,35.000000,12.000000,35.000000,62.000000,9.000000,...,7.000000,5.000000,2.000000,2.000000,12.000000,1.000000,12.000000,2.000000,2.000000,14.000000